version: 2.1

jobs:
  Test:
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Run Tests
          command: echo "Tests Passed"

  Publish_To_NPM:
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Build Package
          command: npm run build
      - run:
          name: Set NPM Auth Token
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
      - run:
          name: Publish to NPM Registry
          command: npm publish --access public

workflows:
  version: 2
  main_workflow:
    jobs:
      - Test:
          filters:
            branches:
              only: main
      - Publish_To_NPM:
          requires:
            - Test
          filters:
            branches:
              only: main
