name: Push to Registry

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check_changes.outputs.should_build }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for GUI or source changes
        id: check_changes
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -E "^(GUI/|src/)" | head -1; then
            echo "should_build=true" >> $GITHUB_OUTPUT
            echo "Changes detected in GUI or source folders"
          else
            echo "should_build=false" >> $GITHUB_OUTPUT
            echo "No changes detected in GUI or source folders"
          fi

  test:
    needs: check-changes
    if: needs.check-changes.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run GUI Build
        run: cd GUI && npm install && npm run build && cd ..
      - name: Move GUI build files
        run: cd ./GUI && mv AxioControl/ ../lib/server/public && cd ..
      - name: Run tests
        run: npm run test

  publish_to_npm:
    needs: [check-changes, test]
    if: needs.check-changes.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Run GUI Build
        run: cd GUI && npm install && npm run build && cd ..
      - name: Move GUI build files
        run: cd ./GUI && mv AxioControl/ ../lib/server/public && cd ..
      - name: Set NPM Auth Token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
      - name: Publish to NPM Registry
        run: npm publish --access public

  publish_to_github:
    needs: [check-changes, test]
    if: needs.check-changes.outputs.should_build == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build package
        run: npm run build
      - name: Run GUI Build
        run: cd GUI && npm install && npm run build && cd ..
      - name: Move GUI build files
        run: cd ./GUI && mv AxioControl/ ../lib/server/public && cd ..
      - name: Set GitHub Auth Token
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GIT_AUTH_TOKEN }}" >> ~/.npmrc
      - name: Change package name in package.json
        run: |
          sudo apt-get update && sudo apt-get install -y sed
          sed -i '2s/"axiodb"/"@${{ secrets.GIT_USER_NAME }}\/axiodb"/' package.json
      - name: Publish to GitHub Package Registry
        run: npm publish --registry=https://npm.pkg.github.com --scope=@${{ secrets.GIT_USER_NAME }} --access public

  skip-deployment:
    needs: check-changes
    if: needs.check-changes.outputs.should_build == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Skip deployment
        run: echo "No GUI or source changes detected. Skipping build and deployment."
